### ISSUE TITLE
思路与论文

### ISSUE THREAD

**Issue by SLDatlantis** [Nagi-ovo/CUMCM2023-C#2]
作者你好，请问可以分享参赛论文吗？如果不方便的话可以讲述一下做题思路呢？

**Comment by Nagi-ovo** [comment]
在 template 文件夹里可以找到 tex 格式的论文，当时刚上手机器学习，做题思路很乱，仅供参考。

**Comment by SLDatlantis** [comment]
> 在 template folder里可以找到 tex 格式的论文，当时刚上手机器学习，做题思路很乱，仅供参考。

作者您好，包裹里的latex论文似乎受损，被提示tex代码出错，并不能被编译为完整的pdf，在每个版块所展示的内容都非常有限，而且您在问题二中的CRITIC法的python实现似乎没有在上传的包中体现，能否告知是用那部分数据完成的呢？单纯的附件二三的合并数据吗？

**Comment by Nagi-ovo** [comment]
> > 在 template folder里可以找到 tex 格式的论文，当时刚上手机器学习，做题思路很乱，仅供参考。
> 
> 作者您好，包裹里的latex论文似乎受损，被提示tex代码出错，并不能被编译为完整的pdf，在每个版块所展示的内容都非常有限，而且您在问题二中的CRITIC法的python实现似乎没有在上传的包中体现，能否告知是用那部分数据完成的呢？单纯的附件二三的合并数据吗？

没什么印象了～不过论文是在overleaf上的XeLatex编译的，另外你说的这部分代码是建模手做的，应该是没发给我收录
